### ISSUE TITLE
Repository maintainer wanted

### ISSUE THREAD

**Issue by mavnn** [mavnn/mintty-colors-solarized#10]
I no longer use mintty myself; if you do and you'd be happy to help maintain the project, do let me know.

**Comment by DoomHammer** [comment]
I find it useful, so in case you're still interested, we can talk about it :)

**Comment by mavnn** [comment]
Hi @DoomHammer ! Thanks for the offer.

To be honest, given the fact I no longer with mintty installed to test changes means that an other maintainer would be great. I'm happy to give you commit access to the repository if that works for you and see how things go from there - to be honest it's not a project with a huge rate of change!

**Comment by DoomHammer** [comment]
I think this'll work. It seems pretty stable and the number of feature requests is moderate, so it should be smooth sailing ;)

**Comment by mavnn** [comment]
If you're feeling super enthusiastic you could even check if the suggestion in https://github.com/mavnn/mintty-colors-solarized/issues/9 works and we'll have a clean issue slate ;)

**Comment by DoomHammer** [comment]
Perfect :)
