### ISSUE TITLE
Some elements are invisible when using dark theme

### ISSUE THREAD

**Issue by tomek** [mavnn/mintty-colors-solarized#2]
I started using solarized dark theme from you few days ago and it looks great, but today I noticed in htop (on remote linux machine) that some elements are invisible (in red circles - there should be current load and cpu/ram percentage) 

![invisible elements are in red circles](http://f.cl.ly/items/2m2Q0u0d2a1K1q3j1N0k/colorissue.png)

**Comment by tkossak** [comment]
It's not only mintty/cygwin problem, i have exactly the same bug on Linux Mint 17 / gnome terminal.

**Comment by mavnn** [comment]
Thanks for the confirm @tkossak  - I'm going to close this one for now, as the basic settings should stay matching solarized. If anyone wants to provide an "alt" scheme that rearranges the colours to avoid this, I'd consider it.
