### ISSUE TITLE
FAQ: nothing changes? Malformed option.

### ISSUE THREAD

**Issue by l-g** [mavnn/mintty-colors-solarized#7]
I downloaded your colour scheme and saved it into a separate file. I then source it from ~/.minttyrc but it does just return an error message "Ignoring malformed option 'source .mintty-colours1'.".

The erroneous line looks like this

source ~/base16-solarized.minttyrc.txt

Regular command line commands does not seem to work in the minttyrc as I am used to for regular unix terminals. Maybe a clarification of the install instructions would make sense?

**Comment by mavnn** [comment]
Hi @l-g ,
there are two ways you can choose to install the colour scheme. One is to take the content of one of .minttyrc files (light or dark) and append it to the .minttyrc file in your user directory. This is the recommended install path.

Other wise, you can source sol.light or sol.dark from a terminal to switch scheme interactively. If you're planning to use one scheme consistently, I would suggest the first route (amending .minttyrc).

Which ever route you go, you should not end up with a ``source`` command in your .minttyrc file.
